import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Button } from 'react-bootstrap'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <TextEditor /> */}
        <Button variant='outline-dark' onClick={() => router.replace('/add-document')}>Add document</Button>
        <Button variant='outline-dark' onClick={() => router.replace('/edit-document')}>Edit document</Button>
      </main>
    </>
  )
}
