import HomepageComponent from '@/components/home'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='container p-5 mt-5'>
          <h1 className='text-center m-5'>Document List</h1>
          <HomepageComponent />
        </div>
      </main>
    </>
  )
}
